apis/urls.py
from django.urls import path
from .views import BookAPIView

urlpatterns = [
    path("", BookAPIView.as_view(), name="book_list"),
]

bankomat/urls.py
from django.urls import path
from .views import BankAccountsView

urlpatterns = [
    path("", BankAccountsView.as_view(), name="bankomat"),
]
  

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("pages.urls")),
    path("", include("books.urls")),
    #path("", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")), # new
    path("bankomat/", include("bankomat.urls")),
    path("api/", include("apis.urls")),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})


class Comment(models.Model):  # new
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("article_list")

bankomat/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Card(models.Model):
    bank_name = models.CharField(max_length=50)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    card_number = models.IntegerField(blank=False, null=False)
    password = models.IntegerField(blank=False, null=False)
    def __str__(self):
        return self.bank_name

    # def get_absolute_url(self):
    #     return reverse("article_detail", kwargs={"pk": self.pk})

bankomat/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import *
# Create your views here.
class BankAccountsView(ListView):
    model = Card
    template_name = "bankomat.html"

templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>Biz Haqimizda</h1>
<p>Assalom alekum <strong>dunyo</strong></p>
<img src="https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/bltedb481d48a78de64/6478e1c1f3e045f9f974dfa5/Crstiano-Ronaldo.jpeg?auto=webp&format=pjpg&width=3840&quality=60" style="width:500px;" alt="">
{% endblock content %}

templates/article_delete.html
{% extends "base.html" %}
{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ article.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/article_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="article-entry">
        <h2>{{ object.title }}</h2>
        <p>by {{ object.author }} | {{ object.date }}</p>
        <p>{{ object.body }}</p>
    </div>
    <hr>
    <h4>Comments</h4>
    {% for comment in article.comment_set.all %}<p>{{ comment.author }} &middot; {{ comment }}</p>{% endfor %}
    <hr>

    <h4>Add a comment</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
    <p>
        <a href="{% url 'article_edit' article.pk %}">Edit</a> |
        <a href="{% url 'article_delete' article.pk %}">Delete</a>
    </p>
    <p>
        Back to <a href="{% url 'article_list' %}">All Articles</a>.
    </p>
{% endblock content %}

templates/article_edit.html
{% extends "base.html" %}
    
{% block content %}
    <h1>Edit</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>
{% endblock content %}

templates/article_list.html
{% extends "base.html" %}
{% block title %}
    Articles
{% endblock title %}
{% block content %}
    {% for article in article_list %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold">{{ article.title }}</span> &middot;
                <span class="text-muted">by {{ article.author }} |
                {{ article.date }}</span>
            </div>
            <div class="card-body">
                <!-- Changes start here! -->
                <p>{{ article.body }}</p>
                <a href="{% url 'article_edit' article.pk %}">Edit</a> |
                <a href="{% url 'article_delete' article.pk %}">Delete</a>
            </div>
            <div class="card-footer">
                {% for comment in article.comment_set.all %}
                    <p>
                        <span class="font-weight-bold">{{ comment.author }} &middot;</span>
                        {{ comment }}
                    </p>
                {% endfor %}
            </div>
        </div>
        <br />
    {% endfor %}
{% endblock content %}

templates/article_new.html
{% extends "base.html" %}

{% block content %}
    <h1>New article</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/bankomat.html
{% extends "base.html" %}
{% block content %}

{% for card in card_list %}
    <div class="post-entry">
        <h2>{{ card.bank_name }}</h2>
        <p>{{ card.card_number }}</p>
    </div>
{% endfor %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Blog Dasturi{% endblock title %}</title>
  <meta name="viewport" content="width=device-width,
  initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <header class="p-3 mb-3 border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center
          justify-content-lg-start">
          <a class="navbar-brand" href="{% url 'home' %}">📚Blog Dasturi</a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
            mb-md-0">
            {% if user.is_authenticated %}
            <li><a href="{% url 'article_new' %}" class="nav-link px-2 link-dark">+ New</a></li>
          </ul>
          <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
              data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="{% url 'password_change'%}">
                  Change password</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </li>
            </ul>
          </div>
          {% else %}
          <div class="text-end">
            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log
              In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
          </div>
          {% endif %}
        </div>
      </div>
    </header>

    <main>
      {% block content %}
      {% endblock content %}
    </main>
  </div>

  <!-- Bootstrap JavaScript Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

{% for post in post_list %}
    <div class="post-entry">
        <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
        <p>{{ post.body|truncatewords:3 }}</p>
    </div>
{% endfor %}

{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}
{% block content %}

<h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}
{% block content %}

<div class="post-entry">
<h2>{{ post.title }}</h2>
<p>{{ post.body }}</p>
</div>

    <p><a href="{% url 'post_edit' post.pk %}">+ Edit Blog Post</a></p>
    <p><a href="{% url 'post_delete' post.pk %}">+ Delete Blog Post</a></p>

{% endblock content %}

templates/post_edit.html
{% extends "base.html" %}
{% block content %}

<h1>Edit post</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Update">
</form>

{% endblock content %}

templates/post_new.html
{% extends "base.html" %}
{% block content %}

    <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}